### ISSUE TITLE
Segmentation fault when destroying chart

### ISSUE THREAD

**Issue by Dalan94** [elvismt/slope#2]
I noticed that there is a segmentation fault when I use the slope_chart_destroy function.
This occurred when destroying the legend with the slope_item_destroy function.
I solved the bug by adding this in the slope_legend_create function.
```C
parent->name = NULL;
parent->metrics = NULL;
```
I don't know if it's a good idea. I let you see.

**Comment by elvismt** [comment]
It seems right. parent->name and parent->metrics are not not used by the
legend, and the way
you prevented the leak is right. I think i have never noticed this bug
because in my test apps
the legend was destroyed in the application exit time, and the segfault
passed unseen.
Good job. thanks.

[image: LSBD] <http://www.lsbd.ufc.br/>

Elvis Teixeira

DEVELOPER

[image: LSBD]elvis.teixeira@lsbd.ufc.br

[image: LSBD]+55 (85) 3366 9235

[image: LSBD]+55 (85) 9135 3008

[image: LSBD]elvis.teixeira
